### ISSUE TITLE
请求使用说明

### ISSUE THREAD

**Issue by cdarlint** [cgddgc/aqniuDownload#1]
你好，看到你使用了flask/js/crx，而且在python中尝试手动aes解密
想问一下最终是如何下载到视频的，能否简要说明一下？
我想参考了用于其他网站，也是qiqiuyun托管的视频，还没研究出来方法

谢谢！

**Comment by cgddgc** [comment]
出于可能造成法律问题的原因这里面的代码不包含aesKey的解密方式，我是通过逆向客户端播放器的JS代码获取到文件的解密算法，如果是其他网站的话方法应该类似，但是算法估计不一样，关键点在于m3u8文件中出现的key并不是数据的真实解密aeskey，真实的aes key解密算法在播放器的js里（此处是player.js，通过m3u8里面的key计算得到），计算出key之后即可解密再拼接文件

**Comment by cdarlint** [comment]
找到了，谢谢
